name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PRODUCTION: ${{ secrets.PRODUCTION }}
      NEXT_PUBLIC_BASE_PATH: /${{ secrets.NEXT_PUBLIC_BASE_PATH }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build:production
    - run: npm run export:production
    - run: touch ./out/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: out
